name: pwi_auth
description: "PWI Cross-Domain Authentication for Flutter"
version: 0.1.3
homepage: "https://github.com/PWI-Works/pwi-auth-flutter"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  http: ^1.2.2
  web: ^1.1.0
  url_launcher: ^6.3.1
  mvvm_plus: ^1.5.4
  flutter_login: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/pwi_logo.png