name: pwi_auth
description: "PWI Cross-Domain Authentication for Flutter"
version: 0.2.19
homepage: "https://github.com/PWI-Works/pwi-auth-flutter"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  http: ^1.2.2
  web: ^1.1.0
  url_launcher: ^6.3.1
  mvvm_plus: ^1.5.4
  flutter_login: ^5.0.0
  flex_color_scheme: ^8.0.2
  flutter_layout_grid: ^2.0.8
  rounded_loading_button_plus: ^3.0.1
  go_router: ^16.2.5
  shared_preferences_web: ^2.4.2
  shared_preferences: ^2.3.5
  cloud_firestore: ^5.6.12
  flutter_adaptive_scaffold: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/pwi-shield-white-space.png